//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbci {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("dbci.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   複数のテーブルデータまたはクエリ結果をCSV出力します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_desc_bulkexp {
            get {
                return ResourceManager.GetString("cmd.desc.bulkexp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   単一のテーブルデータまたはクエリ結果をCSV出力します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_desc_exp {
            get {
                return ResourceManager.GetString("cmd.desc.exp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対話型インターフェースで複数のテーブルデータまたはクエリ結果をCSV出力します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_desc_expi {
            get {
                return ResourceManager.GetString("cmd.desc.expi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV形式のデータをテーブルにインポートします。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_desc_imp {
            get {
                return ResourceManager.GetString("cmd.desc.imp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル名(-t)またはクエリ(-q)を指定してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_message_exp_not_designated {
            get {
                return ResourceManager.GetString("cmd.message.exp.not-designated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   対話型インターフェースを開始しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_message_expi_start {
            get {
                return ResourceManager.GetString("cmd.message.expi.start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @q を入力してエンターを押下すると終了します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_message_general_interactive_exit {
            get {
                return ResourceManager.GetString("cmd.message.general.interactive.exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   @s を入力してエンターを押下すると状態を表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_message_general_interactive_status {
            get {
                return ResourceManager.GetString("cmd.message.general.interactive.status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   すべてのスレッドが終了するのを待機しています... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_message_general_interactive_waiting {
            get {
                return ResourceManager.GetString("cmd.message.general.interactive.waiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   (複数指定可) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_allow_multiple {
            get {
                return ResourceManager.GetString("cmd.prm.general.allow-multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字エンコーディング (UTF-8 | Shift_JIS) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_encoding {
            get {
                return ResourceManager.GetString("cmd.prm.general.encoding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力元ファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_filepath_in {
            get {
                return ResourceManager.GetString("cmd.prm.general.filepath-in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   出力先ファイルパス に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_filepath_out {
            get {
                return ResourceManager.GetString("cmd.prm.general.filepath-out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ヘルプを表示します。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_help {
            get {
                return ResourceManager.GetString("cmd.prm.general.help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   クエリ結果の名前 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_name_for_query {
            get {
                return ResourceManager.GetString("cmd.prm.general.name-for-query", resourceCulture);
            }
        }
        
        /// <summary>
        ///   並列度（使用スレッド/コネクション数） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_parallel {
            get {
                return ResourceManager.GetString("cmd.prm.general.parallel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポートするクエリ に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_query_export {
            get {
                return ResourceManager.GetString("cmd.prm.general.query-export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   エクスポートするテーブル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_table_export {
            get {
                return ResourceManager.GetString("cmd.prm.general.table-export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インポートするテーブル名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_table_import {
            get {
                return ResourceManager.GetString("cmd.prm.general.table-import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   接続先データベース に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_general_target {
            get {
                return ResourceManager.GetString("cmd.prm.general.target", resourceCulture);
            }
        }
        
        /// <summary>
        ///   初期化スクリプト に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string cmd_prm_imp_init {
            get {
                return ResourceManager.GetString("cmd.prm.imp.init", resourceCulture);
            }
        }
    }
}
