-- ITEM
DROP TABLE IF EXISTS ITEM;
CREATE TABLE ITEM (
    ID    INTEGER,
    NAME  TEXT,
    PRICE INTEGER,
    PRIMARY KEY(id)
);

INSERT INTO ITEM (ID, NAME, PRICE) VALUES (1, 'ITEM1', 100);
INSERT INTO ITEM (ID, NAME, PRICE) VALUES (2, 'ITEM2', 200);
INSERT INTO ITEM (ID, NAME, PRICE) VALUES (3, 'ITEM3', 300);

-- SEQ
DROP TABLE IF EXISTS SEQ;
CREATE TABLE SEQ (
    ID    INTEGER
);

INSERT INTO SEQ (ID) values (0);
INSERT INTO SEQ (ID) values (1);
INSERT INTO SEQ (ID) values (2);
INSERT INTO SEQ (ID) values (3);
INSERT INTO SEQ (ID) values (4);
INSERT INTO SEQ (ID) values (5);
INSERT INTO SEQ (ID) values (6);
INSERT INTO SEQ (ID) values (7);
INSERT INTO SEQ (ID) values (8);
INSERT INTO SEQ (ID) values (9);

-- SALE
DROP TABLE IF EXISTS SALE;
CREATE TABLE SALE (
	ID	INTEGER,
	ITEM_ID	INTEGER,
	QTY	INTEGER,
	DESCR	TEXT,
	PRIMARY KEY(ID)
);

INSERT INTO SALE (ID, ITEM_ID, QTY, DESCR)
SELECT
  T1.ID * 100000
+ T2.ID * 10000
+ T3.ID * 1000
+ T4.ID * 100
+ T5.ID * 10
+ 1,
1,
100,
'DESCR'
FROM SEQ T1
CROSS JOIN SEQ T2
CROSS JOIN SEQ T3
CROSS JOIN SEQ T4
CROSS JOIN SEQ T5;


